In [2]:
import numpy as np

a = [0,0,-0.25]
b = [0.2,-0.2,-0.25]
c = [-0.2,-0.2,-0.25]
d = [-0.2,0.2,-0.25]
e = [0.2,0.2,-0.25]
f = [0.2,-0.2,-0.25]
setpoint_array = np.array([a,b,c,d,e,f])

In [3]:
print(setpoint_array)

[[ 0.    0.   -0.25]
 [ 0.2  -0.2  -0.25]
 [-0.2  -0.2  -0.25]
 [-0.2   0.2  -0.25]
 [ 0.2   0.2  -0.25]
 [ 0.2  -0.2  -0.25]]


In [4]:
setpoint_array[0][1]

0.0

In [3]:
from dataclasses import dataclass

# Define a class for individual points
@dataclass
class Point:
    x: float
    y: float
    z: float

# Define a class for setpoints containing multiple points
@dataclass
class Setpoint:
    a: Point
    b: Point
    c: Point
    d: Point
    e: Point
    f: Point

# Initialize the setpoints with the given coordinates
setpoint = Setpoint(
    a=Point(0, 0, -0.25),
    b=Point(0.2, -0.2, -0.25),
    c=Point(-0.2, -0.2, -0.25),
    d=Point(-0.2, 0.2, -0.25),
    e=Point(0.2, 0.2, -0.25),
    f=Point(0.2, -0.2, -0.25)
)

# Accessing the data
print(setpoint.a.x)  # Access x of point a
print(setpoint.b.y)  # Access y of point b
print(setpoint.c.z)  # Access z of point c

0
-0.2
-0.25


In [5]:
for point_name, point in vars(setpoint).items():
    print(f"Point {point_name}: x = {point.x}, y = {point.y}, z = {point.z}")

Point a: x = 0, y = 0, z = -0.25
Point b: x = 0.2, y = -0.2, z = -0.25
Point c: x = -0.2, y = -0.2, z = -0.25
Point d: x = -0.2, y = 0.2, z = -0.25
Point e: x = 0.2, y = 0.2, z = -0.25
Point f: x = 0.2, y = -0.2, z = -0.25
